// Calendar audit: catalogue integrity, matching list/map results and real browser interactions.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const os = require('node:os');
const root = path.resolve(__dirname, '..');
const catalog = JSON.parse(fs.readFileSync(path.join(root, 'data/fiere.json'), 'utf8'));
const { events } = catalog;
const boundaries = JSON.parse(fs.readFileSync(path.join(root, 'data/italia-province.json'), 'utf8'));
require('../js/pages/fiere.js');
const api = globalThis.FiereCalendar;
const regions = [...new Set(events.map(e => e.region))];
assert(events.length > 200);
assert.equal(new Set(events.map(e => e.id)).size, events.length);
assert.equal(regions.length, 20);
const provinces = catalog.provinces;
assert.equal(provinces.length,110);
assert.deepEqual(boundaries.features.map(f => f.properties.name).sort(), provinces.slice().sort());
assert.equal(Object.keys(boundaries.sardiniaMunicipalities).length,377);
for (const region of regions) assert(events.filter(e => e.region === region).length >= 10);
assert.equal(catalog.eventsWithEditionData, events.filter(e => e.editions.length).length);
assert.equal(catalog.eventsWithPublishedDates, events.filter(e => e.editions.some(d => d.start && !d.periodOnly)).length);
for (const event of events) {
    assert(Array.isArray(event.merchandiseSectors));
    assert.equal(new Set(event.merchandiseSectors).size,event.merchandiseSectors.length);
    assert(event.merchandiseSectors.every(sector => Object.hasOwn(api.SECTORS,sector)));
    if (event.merchandiseSectors.some(sector => ['antiquariato','artigianato'].includes(sector))) assert(event.merchandiseSectors.includes('non-alimentare'));
    assert(provinces.includes(event.province));
    if (event.region === 'Sardegna') assert.equal(event.province,boundaries.sardiniaMunicipalities[event.city]);
    assert(event.source.url.startsWith('https://') && event.source.label);
    assert(event.months.every(m => Number.isInteger(m) && m >= 1 && m <= 12));
    assert.equal(new Set(event.months).size, event.months.length);
    assert(['public','selected','exhibitors','check'].includes(event.participation.type));
    assert(event.participation.note);
    if (event.participation.url) assert(event.participation.url.startsWith('https://'));
    if (event.calendarSource) assert(event.calendarSource.url.startsWith('https://'));
    if (event.stallCount) assert(Number.isInteger(event.stallCount) && event.stallCount > 0);
    const signatures = new Set();
    for (const edition of event.editions) {
        assert(['calendar','confirmed'].includes(edition.dateType));
        assert(edition.sourceUrl.startsWith('https://'));
        if (edition.start) {
            assert(/^\d{4}-\d{2}-\d{2}$/.test(edition.start) && edition.start <= edition.end);
            assert.equal(Number(edition.start.slice(0,4)),edition.year);
            assert.equal(new Date(edition.start).toISOString().slice(0,10),edition.start);
            assert.equal(new Date(edition.end).toISOString().slice(0,10),edition.end);
        } else assert(edition.label);
        const signature = JSON.stringify([edition.year,edition.start,edition.end,edition.label]);
        assert(!signatures.has(signature)); signatures.add(signature);
    }
    const [x,y] = api.project(event.lng,event.lat);
    assert(x >= 0 && x <= 660 && y >= 0 && y <= 730, event.city + ' outside map');
}
assert.deepEqual(api.intervalMonths(11, 2), [11,12,1,2]);
assert.deepEqual(api.intervalMonths(4, 4), [4]);
assert.deepEqual(api.intervalMonths(0, 3), []);
const ottobrata = events.find(e => e.name === 'Ottobrata Zafferanese');
assert.deepEqual(ottobrata.editions.map(e => e.start),['2026-10-04','2026-10-11','2026-10-18','2026-10-25']);
assert(ottobrata.editions.every(e => e.start === e.end));
assert.equal(api.selectEdition(ottobrata,'2026-10-09').start,'2026-10-11');
assert.equal(api.selectEdition(ottobrata,'2026-10-18').start,'2026-10-18');
assert.equal(api.editionStatus(ottobrata.editions[0],'2026-10-09'),'Edizione conclusa');
assert.equal(api.selectEdition({editions:[]},'2026-10-09'),null);
const monza = events.find(e => e.city === 'Monza' && e.name === 'Mercatino del brocantage');
assert(monza.editions[0].periodOnly);
assert(api.editionLabel(monza.editions[0]).includes('giorni da verificare'));
assert(api.editionStatus(monza.editions[0],'2026-10-09').startsWith('Appuntamenti periodici'));
const perugia = events.find(e => e.name === 'Fiera dei Morti');
assert(api.deadlineStatus(perugia.participation,'2026-10-09').startsWith('Termine scaduto:'));
const cantu = events.find(e => e.name === 'Fiera del Crocifisso');
assert.deepEqual(cantu.months,[10]);
assert.equal(cantu.editions.find(e => e.year === 2026).start,'2026-10-18');
assert(api.filterEvents(events,{province:'',category:'',months:[],query:'antiquariato'}).some(e => /antiquariato/i.test(e.sectors || '')));
const bySector = sector => events.filter(e => e.merchandiseSectors.includes(sector));
for (const sector of Object.keys(api.SECTORS)) {
    assert(bySector(sector).length > 0);
    assert.deepEqual(api.filterEvents(events,{province:'',category:'',sector,months:[],query:''}),bySector(sector));
}
const antiqueFair = events.find(e => e.name === 'Fiera Antiquaria');
assert(antiqueFair.merchandiseSectors.includes('antiquariato'));
assert(!antiqueFair.merchandiseSectors.includes('alimentare'));
assert(!bySector('alimentare').some(e => ['Non Alimentare','Non Alim.','Non alimentare','prodotti non alimentari'].includes(e.sectors)));
const unknownSectors = events.filter(e => !e.merchandiseSectors.length);
assert(unknownSectors.length > 0);
assert(unknownSectors.every(e => !Object.keys(api.SECTORS).some(sector => api.filterEvents([e],{province:'',category:'',sector,months:[],query:''}).length)));
const mixedFair = events.find(e => e.sectors === 'Alimentare, non Alimentare');
assert(mixedFair.merchandiseSectors.includes('alimentare') && mixedFair.merchandiseSectors.includes('non-alimentare'));
assert(!events.find(e => e.name === 'Mercatino del libro usato').merchandiseSectors.includes('antiquariato'));
for (const province of provinces) {
    const state = {province,category:'tradizionale',months:[10,11],query:''};
    assert.deepEqual(api.filterEvents(events,state), events.filter(e => e.province === province && e.category === 'tradizionale' && e.months.some(m => [10,11].includes(m))));
}
// New official imports: preserve source restrictions and prevent duplicate fairs.
for (const region of ['Liguria','Veneto','Emilia-Romagna']) {
    assert(events.filter(e => e.region === region && e.editions.length).length > 100, region + ' official coverage');
}
const genovaAgata = events.filter(e => e.city === 'Genova' && e.name === "Fiera di Sant'Agata");
assert.equal(genovaAgata.length,1);
assert(genovaAgata[0].calendarSource.url.includes('regione.liguria.it'));
assert(!events.some(e => e.city === 'Genova' && e.name === 'S. AGATA'));
const argenta = events.find(e => e.city === 'Argenta' && e.name === 'Fiera natalizia di Argenta');
assert.deepEqual(argenta.months,[12]);
assert(argenta.editions.every(e => !e.start && e.label.includes('domeniche')));
assert(!events.some(e => e.city === "Castello d'Argile" && e.name === 'FIERA DI LUGLIO'));
const bondeno = events.find(e => e.city === 'Bondeno' && e.name === 'FIERA DI OTTOBRE');
assert.equal(bondeno.stallCount,21);
assert.equal(bondeno.hours,undefined); // The source contains the invalid time 23:90.
assert(bondeno.editions.some(e => e.start === '2026-10-09'));
const dolciumi = events.find(e => e.city === 'Riolo Terme' && e.name === 'SAGRA DELLA ZUCCA E UVA BACCARONA - ASSOCIANDO');
assert(dolciumi.sectors.includes('divieto di somministrazione'));
const borgata = events.find(e => e.city === 'Lugo' && e.name === "FIERA D' AUTUNNO");
assert(borgata.editions.every(e => e.start === '2026-10-25'));
// Audited Brescia coverage overrides contradictory regional dates and groups repeats.
const bresciaResearch = JSON.parse(fs.readFileSync(path.join(root, 'data/fiere-brescia.json'), 'utf8'));
const brescia = events.filter(e => e.province === 'Brescia');
assert.equal(bresciaResearch.province, 'Brescia');
assert.equal(bresciaResearch.checkedAt, '2026-10-09');
assert.equal(brescia.length, bresciaResearch.events.length);
assert(brescia.length >= 200);
assert(brescia.every(e => e.region === 'Lombardia' && e.source.checkedAt === bresciaResearch.checkedAt));
const crocifissa = brescia.find(e => e.name.includes('Crocifissa'));
assert.deepEqual(crocifissa.months, [12]);
assert.equal(crocifissa.editions[0].start, '2026-12-13');
assert.equal(crocifissa.participation.deadline, '2026-10-14');
for (const [city, name, count] of [['Esine', 'Fiera di San Paolo', 2], ["Vezza d'Oglio", 'Fiera del miele', 3], ["Vezza d'Oglio", 'Mercatino del libro usato', 2]]) {
    const matches = brescia.filter(e => e.city === city && e.name === name);
    assert.equal(matches.length, 1);
    assert.equal(matches[0].editions.length, count);
}
const ponteNatale = brescia.find(e => e.city === 'Ponte di Legno' && e.name.startsWith('Mercatini di Natale'));
assert.equal(ponteNatale.participation.deadline, '2026-10-11');
assert.equal(ponteNatale.editions.length, 6);
assert.equal(ponteNatale.editions.reduce((days, e) => days + (Date.parse(e.end) - Date.parse(e.start)) / 86400000 + 1, 0), 29);
assert(ponteNatale.participation.costs.includes('2.500') && ponteNatale.participation.note.includes('29'));
const casoncello = brescia.find(e => e.name.startsWith('Fiera del Casoncello'));
assert.equal(casoncello.editions[0].start, '2026-09-25');
assert(casoncello.participation.note.includes('Vietata la vendita di casoncelli e pasta fresca'));
const quaranti = brescia.find(e => e.name.startsWith('Sagra del Quarantì'));
assert.equal(quaranti.editions[0].start, '2026-08-29');
assert(quaranti.participation.note.includes('vietata la somministrazione'));
assert(quaranti.participation.costs.includes('gratuito'));
const capodanno = brescia.find(e => e.city === 'Borno' && e.name.startsWith('Capodanno'));
assert(capodanno.editions[0].periodOnly);
assert.deepEqual(capodanno.months, [1,12]);
const garda = brescia.find(e => e.name === 'Fiera del Garda');
assert.deepEqual(garda.editions.map(e => [e.start,e.end]), [['2027-02-05','2027-02-07'],['2027-02-12','2027-02-14']]);
const pontagna = brescia.find(e => e.name.includes('Pontagna'));
assert.equal(pontagna.editions[0].start, '2026-09-09');
assert.equal(pontagna.editions[0].end, '2026-09-09');
assert(brescia.find(e => e.city === 'Ghedi' && /Mestieri/i.test(e.name)).editions.every(e => !e.start));
assert(brescia.find(e => e.city === 'Coccaglio' && /Patronale/i.test(e.name)).editions.every(e => !e.start));
const tignaleAutentica = brescia.find(e => e.name.startsWith('Tignale Autentica'));
assert.deepEqual(tignaleAutentica.editions.map(e => e.start), ['2026-05-28','2026-06-18','2026-07-16','2026-09-10']);
assert(tignaleAutentica.editions.every(e => e.start === e.end));
assert.equal(brescia.filter(e => e.city === 'Marone' && /Street Food/i.test(e.name)).length, 3);
// Lodi: market days, cancelled appointments, deadlines and historical editions.
const lodiResearch = JSON.parse(fs.readFileSync(path.join(root, 'data/fiere-lodi.json'), 'utf8'));
const lodi = events.filter(e => e.province === 'Lodi');
assert.equal(lodi.length, 43);
assert.equal(lodi.length, lodiResearch.events.length);
assert.equal(new Set(lodiResearch.research.municipalityCoverage.map(c => c.city)).size, 60);
assert.equal(lodiResearch.research.municipalityCoverage.reduce((sum,c) => sum + c.eventsFound,0), lodi.length);
assert.equal(lodi.filter(e => e.editions.some(d => d.year === 2026)).length,35);
const lodiEvent = (city, pattern) => lodi.find(e => e.city === city && pattern.test(e.name));
assert.equal(lodiEvent("Castiglione d'Adda", /San Bernardino/).editions[0].start,'2026-05-10');
assert.equal(lodiEvent('Brembio', /San Giuseppe/).editions[0].start,'2026-03-15');
assert.equal(lodiEvent("Cavenago d'Adda", /Madonna/).editions[0].start,'2026-03-22');
const codognoVintage = lodiEvent('Codogno', /antiquariato/);
assert.deepEqual(codognoVintage.editions.map(e => e.start),['2026-01-17','2026-02-21','2026-03-21','2026-04-18','2026-05-16','2026-06-20','2026-09-19','2026-10-17','2026-12-19']);
assert.deepEqual(codognoVintage.months,[1,2,3,4,5,6,9,10,12]);
assert.deepEqual(lodi.filter(e => e.city === 'Casaletto Lodigiano').map(e => e.editions[0].start).sort(),['2026-10-11','2026-10-18','2026-10-25']);
const secugnago = lodiEvent('Secugnago', /Natale/);
assert.equal(secugnago.editions[0].start,'2026-12-08');
assert.equal(secugnago.participation.deadline,'2026-11-20');
assert(api.deadlineStatus(secugnago.participation,'2026-10-10').startsWith('Scadenza pubblicata:'));
assert(secugnago.participation.costs.includes('Nessuna quota'));
assert(api.deadlineStatus(lodiEvent('Mulazzano', /Sagra/).participation,'2026-10-10').startsWith('Termine scaduto:'));
assert.equal(lodiEvent('Codogno', /Fiera autunnale/).participation.deadline,'2026-09-23');
assert.deepEqual(lodiEvent('Maleo', /ArteVino/).editions.map(e => e.start),['2026-06-19','2026-06-20','2026-06-21','2026-06-26','2026-06-27','2026-06-28']);
assert(lodiEvent('Lodi', /Santa Lucia/).editions.every(e => e.year === 2025));
assert(lodiEvent('Lodi Vecchio', /Ringraziamento/).editions.every(e => e.year === 2025));
assert(!lodi.some(e => /Passione di Cristo/.test(e.name)));
const server = http.createServer((req,res) => {
    let file = decodeURIComponent(new URL(req.url, 'http://localhost').pathname).slice(1) || 'index.html';
    if (!path.extname(file)) file += '.html';
    const full = path.resolve(root,file);
    if (!full.startsWith(root + path.sep)) return res.writeHead(403).end();
    res.setHeader('Content-Type', ({'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json'})[path.extname(full)] || 'text/plain');
    if (['js/supabase-config.js','js/page-view-tracker.js','js/auth.js'].includes(file)) return res.end('');
    fs.readFile(full, (error,data) => error ? res.writeHead(404).end() : res.end(data));
});

async function run(engine,name,viewport,base) {
    const browser = await engine.launch({headless:true});
    try {
        const context = await browser.newContext({viewport,hasTouch:viewport.width < 720});
        await context.route('**/*', route => new URL(route.request().url()).origin === base ? route.continue() : route.fulfill({status:200,body:''}));
        const page = await context.newPage();
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        async function count(n) {
            await page.waitForFunction(n => document.querySelector('#list-count').textContent === String(n),n);
        }
        async function matches(expected) {
            await count(expected.length);
            const ids = await page.locator('#map-markers > g').evaluateAll(markers => markers.flatMap(m => m.dataset.events.split(',')).sort());
            assert.deepEqual(ids,expected.map(e => e.id).sort());
            const list = await page.locator('.fiere-card').evaluateAll(cards => cards.map(c => c.dataset.eventId));
            assert(list.every(id => ids.includes(id)));
            assert.equal(list.length, Math.min(12,expected.length));
        }
        await page.goto(base + '/fiere');
        await count(events.length);
        assert.equal(await page.locator('#catalog-count').textContent(),String(events.length));
        await page.waitForFunction(() => document.querySelector('#map-provinces').children.length === 110);
        assert.equal(await page.locator('.nav-link-fiere').getAttribute('aria-current'), 'page');
        assert.equal(await page.locator('#month-bar button').count(),12);
        assert.equal(await page.locator('#extra-filters').getAttribute('open'),null);
        assert.equal(await page.locator('#type-filter').isVisible(),false);
        assert.equal(await page.locator('#fair-search').isVisible(),false);
        assert.equal(await page.locator('#month-from').isVisible(),false);
        assert.equal(await page.locator('#province-filter').isVisible(),true);
        assert.equal(await page.locator('#sector-filter').isVisible(),true);
        assert.equal(await page.locator('#sector-filter option').count(),5);
        assert.equal(await page.locator('#province-filter option').count(),111);
        assert.equal(await page.locator('#region-filter').count(),0);
        assert.equal(await page.locator('#month-bar button').first().textContent(),'Gennaio');
        const filtersBox = await page.locator('.fiere-filters').boundingBox();
        const mapBox = await page.locator('.fiere-map-panel').boundingBox();
        const listBox = await page.locator('.fiere-list-panel').boundingBox();
        const headerBox = await page.locator('header').boundingBox();
        assert(Math.abs(filtersBox.y - (headerBox.y + headerBox.height) - 16) < 2,'Filters directly below the header');
        assert(mapBox.y < viewport.height,'Map starts in the first screen');
        if (viewport.width > 720) {
            assert(Math.abs(mapBox.y - filtersBox.y) < 2,'Map beside the primary filters');
            assert(mapBox.x > filtersBox.x + filtersBox.width,'Map to the right');
        } else {
            assert(mapBox.y > filtersBox.y + filtersBox.height,'Map follows the primary filters');
            assert(mapBox.y + mapBox.height < listBox.y,'Map before the results list');
        }
        await matches(events);
        for (const sector of Object.keys(api.SECTORS)) {
            await page.selectOption('#sector-filter',sector);
            await matches(bySector(sector));
            assert.equal(new URL(page.url()).searchParams.get('settore'),sector);
            assert((await page.locator('#results-summary').textContent()).includes(api.SECTORS[sector]));
            await page.reload();
            await matches(bySector(sector));
            assert.equal(await page.locator('#sector-filter').inputValue(),sector);
        }
        await page.selectOption('#province-filter','Lodi');
        await page.selectOption('#sector-filter','antiquariato');
        await page.locator('[data-month="10"]').click();
        const antiqueLodi = events.filter(e => e.province === 'Lodi' && e.months.includes(10) && e.merchandiseSectors.includes('antiquariato'));
        await matches(antiqueLodi);
        assert(antiqueLodi.length > 0);
        await page.locator('#extra-filters > summary').click();
        await page.selectOption('#type-filter','mercatino');
        await page.locator('#fair-search').fill('Codogno');
        await matches(antiqueLodi.filter(e => e.category === 'mercatino' && e.city === 'Codogno'));
        await page.reload();
        await matches(antiqueLodi.filter(e => e.category === 'mercatino' && e.city === 'Codogno'));
        await page.locator('.fiere-card-button').first().click();
        assert((await page.locator('#detail-facts').textContent()).includes('Antiquariato e vintage'));
        await page.keyboard.press('Escape');
        await page.locator('#reset-filters').click();
        await matches(events);
        assert.equal(await page.locator('#sector-filter').inputValue(),'');
        assert.equal(new URL(page.url()).searchParams.get('settore'),null);
        await page.goto(base + '/fiere?settore=inesistente');
        await matches(events);
        assert.equal(await page.locator('#sector-filter').inputValue(),'');
        assert.equal(new URL(page.url()).searchParams.get('settore'),null);
        const firstCard = page.locator('.fiere-card').first();
        const previewProvince = await firstCard.getAttribute('data-province');
        const previewPath = page.locator('#map-provinces [data-province="' + previewProvince + '"]');
        const initialView = await page.locator('#italy-map').getAttribute('viewBox');
        const initialURL = page.url();
        const initialMarkers = await page.locator('#map-markers').innerHTML();
        await firstCard.hover();
        assert.equal(await page.locator('.fiere-province.is-preview').count(),1);
        assert(await previewPath.evaluate(p => p.classList.contains('is-preview')));
        await page.waitForFunction(() => getComputedStyle(document.querySelector('.fiere-province.is-preview')).fill === 'rgb(147, 197, 253)');
        assert.equal(await page.locator('#map-caption').textContent(),previewProvince);
        assert.equal(await page.locator('#province-filter').inputValue(),'');
        assert.equal(await page.locator('.fiere-marker.is-preview').count(),0);
        assert.equal(page.url(),initialURL);
        assert.equal(await page.locator('#italy-map').getAttribute('viewBox'),initialView);
        assert.equal(await page.locator('#map-markers').innerHTML(),initialMarkers,'Hover reuses markers');
        const otherCard = page.locator('.fiere-card').filter({has:page.locator('button')});
        const otherIndex = await otherCard.evaluateAll((cards, region) => cards.findIndex(c => c.dataset.province !== region),previewProvince);
        assert(otherIndex >= 0);
        await otherCard.nth(otherIndex).hover();
        assert.equal(await page.locator('.fiere-province.is-preview').getAttribute('data-province'),await otherCard.nth(otherIndex).getAttribute('data-province'));
        await page.mouse.move(0,0);
        assert.equal(await page.locator('.fiere-province.is-preview').count(),0);
        await firstCard.locator('button').focus();
        assert.equal(await page.locator('.fiere-province.is-preview').getAttribute('data-province'),previewProvince);
        await page.locator('#province-filter').focus();
        assert.equal(await page.locator('.fiere-province.is-preview').count(),0);
        assert.equal(await page.locator('#map-caption').textContent(),'Trascina e ingrandisci');
        await page.locator('#load-more').click();
        assert.equal(await page.locator('.fiere-card').count(),24);
        for (const province of provinces) {
            await page.mouse.move(0,0);
            await page.selectOption('#province-filter',province);
            await matches(events.filter(e => e.province === province));
            assert.equal(await page.locator('.fiere-marker.is-preview').count(),0);
            assert.equal(await page.locator('.fiere-province.is-selected').getAttribute('data-province'),province);
            assert.equal(new URL(page.url()).searchParams.get('provincia'),province);
            assert.equal(new URL(page.url()).searchParams.get('regione'),null);
            if (!events.some(e => e.province === province)) {
                assert(await page.locator('#empty-results').isVisible());
                continue;
            }
            const provincialCard = page.locator('.fiere-card').first();
            const eventId = await provincialCard.getAttribute('data-event-id');
            const provincialEvent = events.find(e => e.id === eventId);
            const provincialURL = page.url();
            const provincialView = await page.locator('#italy-map').getAttribute('viewBox');
            await provincialCard.hover();
            const highlightedMarker = page.locator('.fiere-marker.is-preview');
            assert.equal(await highlightedMarker.count(),1);
            assert((await highlightedMarker.getAttribute('data-events')).split(',').includes(eventId));
            assert.equal(await highlightedMarker.locator('.preview-ring').evaluate(r => getComputedStyle(r).opacity),'1');
            assert.equal(await highlightedMarker.locator('.pin').evaluate(p => getComputedStyle(p).fill),'rgb(37, 99, 235)');
            assert.equal(await page.locator('#map-caption').textContent(),provincialEvent.city);
            assert.equal(await page.locator('.fiere-province.is-preview').count(),0);
            assert.equal(await page.locator('#province-filter').inputValue(),province);
            assert.equal(page.url(),provincialURL);
            assert.equal(await page.locator('#italy-map').getAttribute('viewBox'),provincialView);
            await page.mouse.move(0,0);
            assert.equal(await highlightedMarker.count(),0);
            assert.equal(await page.locator('.fiere-province.is-selected').getAttribute('data-province'),province);
            await provincialCard.locator('button').focus();
            assert.equal(await highlightedMarker.count(),1);
            await page.locator('#map-zoom-in').evaluate(b => b.click());
            assert.equal(await highlightedMarker.count(),1,'Zoom preserves the preview on the new marker group');
            assert((await highlightedMarker.getAttribute('data-events')).split(',').includes(eventId));
            await page.locator('#province-filter').focus();
            assert.equal(await highlightedMarker.count(),0);
        }
        await page.locator('#reset-filters').click();
        assert.equal(await page.locator('#all-months').getAttribute('aria-checked'),'false');
        assert.equal(await page.locator('#all-months').textContent(),'Tutto l’anno');
        assert.equal(await page.locator('#all-months').getAttribute('role'),'switch');
        await page.locator('#all-months').click();
        assert.equal(await page.locator('#month-bar button[aria-pressed="true"]').count(),12);
        assert.equal(await page.locator('#all-months').getAttribute('aria-checked'),'true');
        assert.equal(await page.locator('#all-months').textContent(),'Tutto l’anno');
        await matches(events);
        await page.reload();
        await matches(events);
        assert.equal(await page.locator('#month-bar button[aria-pressed="true"]').count(),12);
        await page.locator('[data-month="11"]').click();
        assert.equal(await page.locator('#month-bar button[aria-pressed="true"]').count(),11);
        assert.equal(await page.locator('#all-months').getAttribute('aria-checked'),'false');
        await matches(events.filter(e => e.months.some(m => m !== 11)));
        await page.locator('#all-months').click();
        assert.equal(await page.locator('#month-bar button[aria-pressed="true"]').count(),12);
        await page.locator('#all-months').click();
        assert.equal(await page.locator('#month-bar button[aria-pressed="true"]').count(),0);
        assert.equal(await page.locator('#all-months').getAttribute('aria-checked'),'false');
        assert.equal(new URL(page.url()).searchParams.get('mesi'),null);
        await matches(events);
        await page.locator('[data-month="11"]').click();
        await matches(events.filter(e => e.months.includes(11)));
        await page.locator('[data-month="12"]').click();
        await matches(events.filter(e => e.months.some(m => [11,12].includes(m))));
        await page.locator('#extra-filters > summary').click();
        assert(await page.locator('#type-filter').isVisible());
        await page.selectOption('#month-from','11');
        await page.selectOption('#month-to','2');
        await matches(events.filter(e => e.months.some(m => [11,12,1,2].includes(m))));
        assert.equal(new URL(page.url()).searchParams.get('mesi'),'11,12,1,2');
        await page.reload();
        await matches(events.filter(e => e.months.some(m => [11,12,1,2].includes(m))));
        await page.locator('#extra-filters > summary').click();
        await page.selectOption('#type-filter','tradizionale');
        await matches(events.filter(e => e.category === 'tradizionale' && e.months.some(m => [11,12,1,2].includes(m))));
        assert.equal(await page.locator('#extra-filter-count').textContent(),'1');
        await page.locator('#extra-filters > summary').click();
        assert(await page.locator('#extra-filter-count').isVisible());
        await page.reload();
        await matches(events.filter(e => e.category === 'tradizionale' && e.months.some(m => [11,12,1,2].includes(m))));
        assert(await page.locator('#extra-filter-count').isVisible());
        await page.locator('#reset-filters').click();
        assert.equal(await page.locator('#extra-filter-count').isVisible(),false);
        await page.locator('#extra-filters > summary').click();
        await page.locator('#fair-search').fill('CARRU');
        await matches(api.filterEvents(events,{province:'',category:'',months:[],query:'CARRU'}));
        const carru = events.find(e => e.city === 'Carrù');
        await page.locator('.fiere-card[data-event-id="' + carru.id + '"] .fiere-card-button').click();
        assert.equal(await page.locator('#fair-dialog').evaluate(d => d.open),true);
        assert.equal(await page.locator('#detail-source').getAttribute('href'),events.find(e => e.city === 'Carrù').source.url);
        assert((await page.locator('#detail-editions').textContent()).includes('17 dic 2026'));
        assert((await page.locator('#detail-participation-note').textContent()).length > 20);
        await page.keyboard.press('Escape');
        await page.waitForFunction(() => !document.querySelector('#fair-dialog').open);
        await page.locator('#fair-search').fill('Fiera dei Morti');
        await matches(api.filterEvents(events,{province:'',category:'',months:[],query:'Fiera dei Morti'}));
        await page.locator('.fiere-card[data-event-id="' + perugia.id + '"] .fiere-card-button').click();
        assert.equal(await page.locator('#detail-participation-link').getAttribute('href'),perugia.participation.url);
        assert((await page.locator('#detail-deadline').textContent()).includes('1 lug 2026'));
        assert((await page.locator('#detail-contacts').textContent()).includes('suape@pec.comune.perugia.it'));
        assert.equal(await page.locator('#detail-editions a').getAttribute('href'),perugia.editions[0].sourceUrl);
        assert.equal(await page.locator('#fair-dialog').evaluate(d => d.scrollWidth > d.clientWidth),false,'Detail overflow');
        await page.locator('#fair-dialog').screenshot({path:path.join(os.tmpdir(),'subingresso-fiere-detail-'+name+'-'+viewport.width+'.png')});
        await page.keyboard.press('Escape');
        await page.waitForFunction(() => !document.querySelector('#fair-dialog').open);
        await page.locator('#fair-search').fill('Ottobrata Zafferanese');
        await matches([ottobrata]);
        await page.locator('.fiere-card-button').click();
        assert.equal(await page.locator('#detail-editions > div').count(),4);
        await page.keyboard.press('Escape');
        await page.waitForFunction(() => !document.querySelector('#fair-dialog').open);
        await page.locator('#fair-search').fill('zzzz-no-result');
        await matches([]);
        assert(await page.locator('#empty-results').isVisible());
        await page.locator('#empty-reset').click();
        await count(events.length);
        const brescia = page.locator('#map-provinces [data-province="Brescia"]');
        await brescia.focus(); await page.keyboard.press('Enter');
        await matches(events.filter(e => e.province === 'Brescia'));
        assert.equal(await page.locator('#province-filter').inputValue(),'Brescia');
        await page.reload();
        await matches(events.filter(e => e.province === 'Brescia'));
        await page.waitForFunction(() => document.querySelector('.fiere-province.is-selected')?.dataset.province === 'Brescia');
        await page.locator('[data-month="10"]').click();
        await matches(events.filter(e => e.province === 'Brescia' && e.months.includes(10)));
        await page.locator('#extra-filters > summary').click();
        await page.selectOption('#type-filter','tradizionale');
        await matches(events.filter(e => e.province === 'Brescia' && e.category === 'tradizionale' && e.months.includes(10)));
        await page.reload();
        await matches(events.filter(e => e.province === 'Brescia' && e.category === 'tradizionale' && e.months.includes(10)));
        await page.locator('#reset-filters').click();
        await page.selectOption('#province-filter','Brescia');
        await matches(events.filter(e => e.province === 'Brescia'));
        const marker = page.locator('#map-markers > g').first();
        await marker.focus(); await page.keyboard.press('Enter');
        assert(await page.locator('#map-popup').isVisible());
        await page.locator('.fiere-popup-event').first().click();
        assert.equal(await page.locator('#fair-dialog').evaluate(d => d.open),true);
        await page.locator('#close-detail').click();
        await page.goto(base + '/fiere?provincia=Lodi');
        await matches(lodi);
        await page.goto(base + '/fiere?provincia=Lodi&q=Secugnago');
        await matches([secugnago]);
        await page.locator('.fiere-card-button').click();
        assert((await page.locator('#detail-deadline').textContent()).includes('20 nov 2026'));
        assert((await page.locator('#detail-costs').textContent()).includes('Nessuna quota'));
        assert.equal(await page.locator('#detail-participation-link').getAttribute('href'),secugnago.participation.url);
        await page.locator('#close-detail').click();
        await page.goto(base + '/fiere?provincia=Lodi&mesi=10');
        await matches(lodi.filter(e => e.months.includes(10)));
        await page.reload();
        await matches(lodi.filter(e => e.months.includes(10)));
        await page.locator('#reset-filters').click();
        await count(events.length);
        const before = await page.locator('#italy-map').getAttribute('viewBox');
        await page.locator('#map-zoom-in').click();
        assert.notEqual(await page.locator('#italy-map').getAttribute('viewBox'),before);
        await page.locator('#map-home').click();
        assert.equal(await page.locator('#italy-map').getAttribute('viewBox'),before);
        await page.locator('#italy-map').scrollIntoViewIfNeeded();
        const mapArea = await page.locator('#italy-map').boundingBox();
        const mx = mapArea.x + mapArea.width * .35, my = mapArea.y + mapArea.height * .45;
        await page.mouse.move(mx,my);
        await page.mouse.wheel(0,-450);
        await page.waitForFunction(home => Number(document.querySelector('#italy-map').getAttribute('viewBox').split(' ')[2]) < Number(home.split(' ')[2]),before);
        const zoomed = await page.locator('#italy-map').getAttribute('viewBox');
        await page.waitForFunction(initial => document.querySelector('#map-markers').children.length > initial,
            api.clusterEvents(events,28*Math.max(660/mapArea.width,730/mapArea.height)).length);
        const markersBeforeDrag = await page.locator('#map-markers > g').count();
        await page.evaluate(() => {
            window.markerChanges = 0;
            window.markerObserver = new MutationObserver(changes => { window.markerChanges += changes.length; });
            window.markerObserver.observe(document.querySelector('#map-markers'),{childList:true});
        });
        await page.mouse.down();
        await page.mouse.move(mx+55,my+35,{steps:5});
        await page.mouse.up();
        const dragged = await page.locator('#italy-map').getAttribute('viewBox');
        assert.notEqual(dragged,zoomed,'Drag moves the map');
        assert.equal(dragged.split(' ')[2],zoomed.split(' ')[2],'Drag preserves zoom');
        assert.equal(await page.locator('#province-filter').inputValue(),'','Drag must not select a province');
        assert.equal(await page.locator('#map-popup').isVisible(),false,'Drag must not open a marker');
        assert.equal(await page.locator('#map-markers > g').count(),markersBeforeDrag);
        assert.equal(await page.evaluate(() => window.markerChanges),0,'Drag reuses the markers');
        await page.evaluate(() => { window.markerObserver.disconnect(); });
        await page.locator('#italy-map').evaluate((map, pos) => {
            const send = (type,id,x) => map.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:id,pointerType:'touch',button:0,clientX:x,clientY:pos.y}));
            send('pointerdown',21,pos.x-30); send('pointerdown',22,pos.x+30);
            send('pointermove',22,pos.x+90);
            send('pointerup',21,pos.x-30); send('pointerup',22,pos.x+90);
        },{x:mx,y:my});
        assert(Number((await page.locator('#italy-map').getAttribute('viewBox')).split(' ')[2]) < Number(dragged.split(' ')[2]),'Two fingers zoom in');
        await page.locator('#map-home').click();
        assert.equal(await page.locator('#italy-map').getAttribute('viewBox'),before);
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false,'Horizontal overflow');
        await page.locator('#extra-filters > summary').click();
        await page.evaluate(() => window.scrollTo(0,0));
        await page.screenshot({path:path.join(os.tmpdir(),'subingresso-fiere-'+name+'-'+viewport.width+'.png'),fullPage:false});
        await page.locator('.fiere-map-panel').screenshot({path:path.join(os.tmpdir(),'subingresso-fiere-map-'+name+'-'+viewport.width+'.png')});

        // A failed request must be recoverable without reloading the page.
        let failCatalog = true;
        await context.route('**/data/fiere.json?*', route => failCatalog ? route.fulfill({status:503,body:'unavailable'}) : route.continue());
        await page.reload();
        await page.locator('#catalog-error').waitFor({state:'visible'});
        failCatalog = false;
        await page.locator('#retry-catalog').click();
        await count(events.length);
        let failMap = true;
        await context.route('**/data/italia-province.json?*', route => failMap ? route.fulfill({status:503,body:'unavailable'}) : route.continue());
        await page.reload();
        await page.locator('#map-error').waitFor({state:'visible'});
        await count(events.length);
        failMap = false;
        await page.locator('#retry-map').click();
        await page.waitForFunction(() => document.querySelector('#map-provinces').children.length === 110);
        assert.equal(await page.locator('#map-error').isVisible(),false);
        await page.goto(base + '/fiere?regione=Lombardia&provincia=inesistente&mesi=10&tipo=tradizionale');
        await matches(events.filter(e => e.category === 'tradizionale' && e.months.includes(10)));
        assert.equal(await page.locator('#province-filter').inputValue(),'');
        assert.equal(new URL(page.url()).searchParams.get('regione'),null);
        assert.equal(new URL(page.url()).searchParams.get('provincia'),null);
        assert.deepEqual(errors,[]);
        console.log(name + ' ' + viewport.width + ': passed filters, all provinces, list/map consistency, details, keyboard, retries and overflow');
    } finally { await browser.close(); }
}
(async () => {
    const playwright = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
    await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
    const base = 'http://127.0.0.1:' + server.address().port;
    try {
        await run(playwright.chromium,'chromium',{width:1440,height:1100},base);
        await run(playwright.chromium,'chromium',{width:820,height:1000},base);
        await run(playwright.chromium,'chromium',{width:390,height:844},base);
        await run(playwright.webkit,'webkit',{width:390,height:844},base);
        await run(playwright.chromium,'chromium',{width:320,height:800},base);
        console.log('Catalogue: ' + events.length + ' unique events, 20 regions; editions, participation, sources and coordinates validated.');
    } finally { await new Promise(resolve => server.close(resolve)); }
})().catch(error => {console.error(error);process.exitCode=1;server.close();});
