// ============================================================
//  Lista capoluoghi italiani per pagine SEO geo (/annunci/[citta])
//  Importata da api/annunci-citta.js e api/sitemap.js.
//  Le pagine di queste città sono sempre indicizzabili (200 OK)
//  anche senza annunci attivi: il template mostra placeholder
//  utile + CTA invece di 404.
// ============================================================

// 105 capoluoghi di provincia + 5 città turistiche/mercatali notevoli
// (Sirmione, Riccione, Taormina, Capri, Cortina) per coprire query geo forti.
const CAPOLUOGHI = [
    { slug: 'agrigento',         name: 'Agrigento',         regione: 'Sicilia' },
    { slug: 'alessandria',       name: 'Alessandria',       regione: 'Piemonte' },
    { slug: 'ancona',            name: 'Ancona',            regione: 'Marche' },
    { slug: 'aosta',             name: 'Aosta',             regione: "Valle d'Aosta" },
    { slug: 'arezzo',            name: 'Arezzo',            regione: 'Toscana' },
    { slug: 'ascoli-piceno',     name: 'Ascoli Piceno',     regione: 'Marche' },
    { slug: 'asti',              name: 'Asti',              regione: 'Piemonte' },
    { slug: 'avellino',          name: 'Avellino',          regione: 'Campania' },
    { slug: 'bari',              name: 'Bari',              regione: 'Puglia' },
    { slug: 'barletta',          name: 'Barletta',          regione: 'Puglia' },
    { slug: 'belluno',           name: 'Belluno',           regione: 'Veneto' },
    { slug: 'benevento',         name: 'Benevento',         regione: 'Campania' },
    { slug: 'bergamo',           name: 'Bergamo',           regione: 'Lombardia' },
    { slug: 'biella',            name: 'Biella',            regione: 'Piemonte' },
    { slug: 'bologna',           name: 'Bologna',           regione: 'Emilia-Romagna' },
    { slug: 'bolzano',           name: 'Bolzano',           regione: 'Trentino-Alto Adige' },
    { slug: 'brescia',           name: 'Brescia',           regione: 'Lombardia' },
    { slug: 'brindisi',          name: 'Brindisi',          regione: 'Puglia' },
    { slug: 'cagliari',          name: 'Cagliari',          regione: 'Sardegna' },
    { slug: 'caltanissetta',     name: 'Caltanissetta',     regione: 'Sicilia' },
    { slug: 'campobasso',        name: 'Campobasso',        regione: 'Molise' },
    { slug: 'caserta',           name: 'Caserta',           regione: 'Campania' },
    { slug: 'catania',           name: 'Catania',           regione: 'Sicilia' },
    { slug: 'catanzaro',         name: 'Catanzaro',         regione: 'Calabria' },
    { slug: 'chieti',            name: 'Chieti',            regione: 'Abruzzo' },
    { slug: 'como',              name: 'Como',              regione: 'Lombardia' },
    { slug: 'cosenza',           name: 'Cosenza',           regione: 'Calabria' },
    { slug: 'cremona',           name: 'Cremona',           regione: 'Lombardia' },
    { slug: 'crotone',           name: 'Crotone',           regione: 'Calabria' },
    { slug: 'cuneo',             name: 'Cuneo',             regione: 'Piemonte' },
    { slug: 'enna',              name: 'Enna',              regione: 'Sicilia' },
    { slug: 'fermo',             name: 'Fermo',             regione: 'Marche' },
    { slug: 'ferrara',           name: 'Ferrara',           regione: 'Emilia-Romagna' },
    { slug: 'firenze',           name: 'Firenze',           regione: 'Toscana' },
    { slug: 'foggia',            name: 'Foggia',            regione: 'Puglia' },
    { slug: 'forli',             name: 'Forlì',             regione: 'Emilia-Romagna' },
    { slug: 'frosinone',         name: 'Frosinone',         regione: 'Lazio' },
    { slug: 'genova',            name: 'Genova',            regione: 'Liguria' },
    { slug: 'gorizia',           name: 'Gorizia',           regione: 'Friuli-Venezia Giulia' },
    { slug: 'grosseto',          name: 'Grosseto',          regione: 'Toscana' },
    { slug: 'imperia',           name: 'Imperia',           regione: 'Liguria' },
    { slug: 'isernia',           name: 'Isernia',           regione: 'Molise' },
    { slug: 'la-spezia',         name: 'La Spezia',         regione: 'Liguria' },
    { slug: 'l-aquila',          name: "L'Aquila",          regione: 'Abruzzo' },
    { slug: 'latina',            name: 'Latina',            regione: 'Lazio' },
    { slug: 'lecce',             name: 'Lecce',             regione: 'Puglia' },
    { slug: 'lecco',             name: 'Lecco',             regione: 'Lombardia' },
    { slug: 'livorno',           name: 'Livorno',           regione: 'Toscana' },
    { slug: 'lodi',              name: 'Lodi',              regione: 'Lombardia' },
    { slug: 'lucca',             name: 'Lucca',             regione: 'Toscana' },
    { slug: 'macerata',          name: 'Macerata',          regione: 'Marche' },
    { slug: 'mantova',           name: 'Mantova',           regione: 'Lombardia' },
    { slug: 'massa',             name: 'Massa',             regione: 'Toscana' },
    { slug: 'matera',            name: 'Matera',            regione: 'Basilicata' },
    { slug: 'messina',           name: 'Messina',           regione: 'Sicilia' },
    { slug: 'milano',            name: 'Milano',            regione: 'Lombardia' },
    { slug: 'modena',            name: 'Modena',            regione: 'Emilia-Romagna' },
    { slug: 'monza',             name: 'Monza',             regione: 'Lombardia' },
    { slug: 'napoli',            name: 'Napoli',            regione: 'Campania' },
    { slug: 'novara',            name: 'Novara',            regione: 'Piemonte' },
    { slug: 'nuoro',             name: 'Nuoro',             regione: 'Sardegna' },
    { slug: 'oristano',          name: 'Oristano',          regione: 'Sardegna' },
    { slug: 'padova',            name: 'Padova',            regione: 'Veneto' },
    { slug: 'palermo',           name: 'Palermo',           regione: 'Sicilia' },
    { slug: 'parma',             name: 'Parma',             regione: 'Emilia-Romagna' },
    { slug: 'pavia',             name: 'Pavia',             regione: 'Lombardia' },
    { slug: 'perugia',           name: 'Perugia',           regione: 'Umbria' },
    { slug: 'pesaro',            name: 'Pesaro',            regione: 'Marche' },
    { slug: 'pescara',           name: 'Pescara',           regione: 'Abruzzo' },
    { slug: 'piacenza',          name: 'Piacenza',          regione: 'Emilia-Romagna' },
    { slug: 'pisa',              name: 'Pisa',              regione: 'Toscana' },
    { slug: 'pistoia',           name: 'Pistoia',           regione: 'Toscana' },
    { slug: 'pordenone',         name: 'Pordenone',         regione: 'Friuli-Venezia Giulia' },
    { slug: 'potenza',           name: 'Potenza',           regione: 'Basilicata' },
    { slug: 'prato',             name: 'Prato',             regione: 'Toscana' },
    { slug: 'ragusa',            name: 'Ragusa',            regione: 'Sicilia' },
    { slug: 'ravenna',           name: 'Ravenna',           regione: 'Emilia-Romagna' },
    { slug: 'reggio-calabria',   name: 'Reggio Calabria',   regione: 'Calabria' },
    { slug: 'reggio-emilia',     name: 'Reggio Emilia',     regione: 'Emilia-Romagna' },
    { slug: 'rieti',             name: 'Rieti',             regione: 'Lazio' },
    { slug: 'rimini',            name: 'Rimini',            regione: 'Emilia-Romagna' },
    { slug: 'roma',              name: 'Roma',              regione: 'Lazio' },
    { slug: 'rovigo',            name: 'Rovigo',            regione: 'Veneto' },
    { slug: 'salerno',           name: 'Salerno',           regione: 'Campania' },
    { slug: 'sassari',           name: 'Sassari',           regione: 'Sardegna' },
    { slug: 'savona',            name: 'Savona',            regione: 'Liguria' },
    { slug: 'siena',             name: 'Siena',             regione: 'Toscana' },
    { slug: 'siracusa',          name: 'Siracusa',          regione: 'Sicilia' },
    { slug: 'sondrio',           name: 'Sondrio',           regione: 'Lombardia' },
    { slug: 'taranto',           name: 'Taranto',           regione: 'Puglia' },
    { slug: 'teramo',            name: 'Teramo',            regione: 'Abruzzo' },
    { slug: 'terni',             name: 'Terni',             regione: 'Umbria' },
    { slug: 'torino',            name: 'Torino',            regione: 'Piemonte' },
    { slug: 'trapani',           name: 'Trapani',           regione: 'Sicilia' },
    { slug: 'trento',            name: 'Trento',            regione: 'Trentino-Alto Adige' },
    { slug: 'treviso',           name: 'Treviso',           regione: 'Veneto' },
    { slug: 'trieste',           name: 'Trieste',           regione: 'Friuli-Venezia Giulia' },
    { slug: 'udine',             name: 'Udine',             regione: 'Friuli-Venezia Giulia' },
    { slug: 'varese',            name: 'Varese',            regione: 'Lombardia' },
    { slug: 'venezia',           name: 'Venezia',           regione: 'Veneto' },
    { slug: 'verbania',          name: 'Verbania',          regione: 'Piemonte' },
    { slug: 'vercelli',          name: 'Vercelli',          regione: 'Piemonte' },
    { slug: 'verona',            name: 'Verona',            regione: 'Veneto' },
    { slug: 'vibo-valentia',     name: 'Vibo Valentia',     regione: 'Calabria' },
    { slug: 'vicenza',           name: 'Vicenza',           regione: 'Veneto' },
    { slug: 'viterbo',           name: 'Viterbo',           regione: 'Lazio' },
    // Città turistiche / mercatali non capoluogo (forte query SEO)
    { slug: 'sirmione',           name: 'Sirmione',            regione: 'Lombardia' },
    { slug: 'riccione',           name: 'Riccione',            regione: 'Emilia-Romagna' },
    { slug: 'taormina',           name: 'Taormina',            regione: 'Sicilia' },
    { slug: 'capri',              name: 'Capri',               regione: 'Campania' },
    { slug: 'cortina-d-ampezzo',  name: "Cortina d'Ampezzo",   regione: 'Veneto' },
    { slug: 'sanremo',            name: 'Sanremo',             regione: 'Liguria' },
    { slug: 'jesolo',             name: 'Jesolo',              regione: 'Veneto' },
    { slug: 'gallipoli',          name: 'Gallipoli',           regione: 'Puglia' },
    { slug: 'cefalu',             name: 'Cefalù',              regione: 'Sicilia' },
    // Lago di Garda + Romagna (gli annunci attuali sono concentrati qui — slug stabile per ricerca)
    { slug: 'salo',               name: 'Salò',                regione: 'Lombardia' },
    { slug: 'desenzano-del-garda',name: 'Desenzano del Garda', regione: 'Lombardia' },
    { slug: 'lazise',             name: 'Lazise',              regione: 'Veneto' },
    { slug: 'peschiera-del-garda',name: 'Peschiera del Garda', regione: 'Veneto' },
    { slug: 'manerba-del-garda',  name: 'Manerba del Garda',   regione: 'Lombardia' },
    { slug: 'moniga-del-garda',   name: 'Moniga del Garda',    regione: 'Lombardia' },
    { slug: 'torri-del-benaco',   name: 'Torri del Benaco',    regione: 'Veneto' },
    { slug: 'toscolano-maderno',  name: 'Toscolano Maderno',   regione: 'Lombardia' },
    { slug: 'bardolino',          name: 'Bardolino',           regione: 'Veneto' },
    { slug: 'malcesine',          name: 'Malcesine',           regione: 'Veneto' },
    { slug: 'cesena',             name: 'Cesena',              regione: 'Emilia-Romagna' },
    // Riviera adriatica + altre piazze turistiche
    { slug: 'cervia',             name: 'Cervia',              regione: 'Emilia-Romagna' },
    { slug: 'cesenatico',         name: 'Cesenatico',          regione: 'Emilia-Romagna' },
    { slug: 'cattolica',          name: 'Cattolica',           regione: 'Emilia-Romagna' },
    { slug: 'caorle',             name: 'Caorle',              regione: 'Veneto' },
    { slug: 'bibione',            name: 'Bibione',             regione: 'Veneto' },
    { slug: 'alassio',            name: 'Alassio',             regione: 'Liguria' },
    { slug: 'rapallo',            name: 'Rapallo',             regione: 'Liguria' },
    { slug: 'sestri-levante',     name: 'Sestri Levante',      regione: 'Liguria' },
    { slug: 'otranto',            name: 'Otranto',             regione: 'Puglia' },
    { slug: 'vieste',             name: 'Vieste',              regione: 'Puglia' },
    { slug: 'tropea',             name: 'Tropea',              regione: 'Calabria' },
];

const CAPOLUOGHI_BY_SLUG = Object.fromEntries(CAPOLUOGHI.map(c => [c.slug, c]));

module.exports = { CAPOLUOGHI, CAPOLUOGHI_BY_SLUG };
